openapi: 3.0.0
info:
  title: movie-review-api
  version: 0.0.1
  description: movie-review-api
paths:
  /movies/recommended:
    get:
      summary: おすすめの映画リストを返却する
      responses:
        '200':
          description: 映画のリスト
          content:
            application/json:
              schema:
                type: object
                properties:
                  movies:
                    type: array
                    items:
                      $ref: '#/components/schemas/MovieSummary'
components:
  schemas:
    MovieSummary:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        backdrop_url:
          type: string
        rating:
          type: number
          format: double
          minimum: 0
          maximum: 5.00
          multipleOf: 0.01
